model_provider = "minimax"
model_context_window = 524288
preferred_auth_method = "apikey"
forced_login_method = "api"

[model_providers.minimax]
name = "MiniMax"
base_url = "https://api.minimax.cn/v1"
experimental_bearer_token = "<YOUR_API_KEY>"
wire_api = "responses"